-- ==========================================
-- 1. TABELLE "profiles" ERSTELLEN
-- ==========================================
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  username TEXT UNIQUE NOT NULL,
  email TEXT UNIQUE NOT NULL,
  games_played INTEGER NOT NULL DEFAULT 0,
  games_won INTEGER NOT NULL DEFAULT 0,
  high_score INTEGER NOT NULL DEFAULT 0,
  total_points INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Indizes für schnelle Abfragen erstellen
CREATE INDEX IF NOT EXISTS idx_profiles_username ON public.profiles(username);
CREATE INDEX IF NOT EXISTS idx_profiles_email ON public.profiles(email);

-- ==========================================
-- 2. ROW LEVEL SECURITY (RLS) AKTIVIEREN & POLICIES
-- ==========================================
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- 2.1 Lesezugriff: Angemeldete Benutzer können alle Profile einsehen (z.B. für Leaderboards oder Benutzernamen-Login)
CREATE POLICY "Profile für angemeldete Nutzer lesbar" 
  ON public.profiles 
  FOR SELECT 
  TO authenticated 
  USING (true);

-- 2.2 Schreibzugriff (Insert): Benutzer können ihr eigenes Profil anlegen
CREATE POLICY "Eigenes Profil anlegen" 
  ON public.profiles 
  FOR INSERT 
  TO authenticated 
  WITH CHECK (auth.uid() = id);

-- 2.3 Schreibzugriff (Update): Benutzer können nur ihr eigenes Profil aktualisieren
CREATE POLICY "Eigenes Profil aktualisieren" 
  ON public.profiles 
  FOR UPDATE 
  TO authenticated 
  USING (auth.uid() = id) 
  WITH CHECK (auth.uid() = id);

-- ==========================================
-- 3. DATABASE TRIGGER ZUR AUTOMATISCHEN PROFIL-ERSTELLUNG
-- ==========================================
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER 
LANGUAGE plpgsql 
SECURITY DEFINER SET search_path = public
AS $$
BEGIN
  INSERT INTO public.profiles (id, email, username)
  VALUES (
    new.id,
    new.email,
    COALESCE(new.raw_user_meta_data->>'username', SPLIT_PART(new.email, '@', 1))
  )
  ON CONFLICT (id) DO UPDATE SET
    email = EXCLUDED.email,
    username = COALESCE(EXCLUDED.username, public.profiles.username);
  RETURN new;
END;
$$;

-- Trigger an die auth.users Tabelle binden
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- ==========================================
-- 4. OPTIONALE DATABASE-FUNKTION (RPC) FÜR ATOMARE STATS-UPDATES
-- ==========================================
CREATE OR REPLACE FUNCTION public.update_game_stats(
  p_user_id UUID,
  p_score INTEGER,
  p_is_win BOOLEAN
)
RETURNS public.profiles
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_profile public.profiles;
BEGIN
  UPDATE public.profiles
  SET 
    games_played = games_played + 1,
    games_won = games_won + CASE WHEN p_is_win THEN 1 ELSE 0 END,
    total_points = total_points + p_score,
    high_score = GREATEST(high_score, p_score)
  WHERE id = p_user_id
  RETURNING * INTO v_profile;

  RETURN v_profile;
END;
$$;

-- ==========================================
-- 5. STAGING-TABELLEN (FÜR MIGRATION & ROHDATEN)
-- ==========================================
-- 5.1 Staging-Tabelle für results.csv
CREATE TABLE IF NOT EXISTS public.staging_results_csv (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  raw_line TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 5.2 Staging-Tabelle für Turnier-Rohdaten
CREATE TABLE IF NOT EXISTS public.staging_tournaments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tournament_name TEXT NOT NULL,
  raw_line TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Indizes für schnelle Abfragen
CREATE INDEX IF NOT EXISTS idx_staging_results_csv_created ON public.staging_results_csv(created_at);
CREATE INDEX IF NOT EXISTS idx_staging_tournaments_name ON public.staging_tournaments(tournament_name);

-- RLS aktivieren & Zugriffsregeln
ALTER TABLE public.staging_results_csv ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.staging_tournaments ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow service role all staging_results_csv" 
  ON public.staging_results_csv 
  FOR ALL 
  TO service_role 
  USING (true);

CREATE POLICY "Allow service role all staging_tournaments" 
  ON public.staging_tournaments 
  FOR ALL 
  TO service_role 
  USING (true);

-- ==========================================
-- 6. HILFSFUNKTION FÜR DYNAMISCHE SQL-AUSFÜHRUNG (ADMIN)
-- ==========================================
CREATE OR REPLACE FUNCTION public.exec_sql(sql text)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  EXECUTE sql;
END;
$$;

-- ==========================================
-- 7. TABELLE "game_results" (ERGEBNISSE & STATISTIKEN)
-- ==========================================
CREATE TABLE IF NOT EXISTS public.game_results (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  is_guest BOOLEAN DEFAULT false,
  player_name TEXT,
  game_mode TEXT NOT NULL,
  date TEXT NOT NULL,
  avg NUMERIC(8,2) NOT NULL DEFAULT 0,
  schnaepse INTEGER NOT NULL DEFAULT 0,
  time_seconds NUMERIC(8,2),
  total NUMERIC(8,2) NOT NULL DEFAULT 0,
  levels INTEGER,
  team_name TEXT,
  tournament_name TEXT,
  tournament_table TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Falls Tabelle schon existiert, fehlende Spalten idempotent ergänzen:
ALTER TABLE public.game_results ADD COLUMN IF NOT EXISTS is_guest BOOLEAN DEFAULT false;
ALTER TABLE public.game_results ADD COLUMN IF NOT EXISTS player_name TEXT;
ALTER TABLE public.game_results ADD COLUMN IF NOT EXISTS tournament_name TEXT;
ALTER TABLE public.game_results ADD COLUMN IF NOT EXISTS tournament_table TEXT;
ALTER TABLE public.game_results ADD COLUMN IF NOT EXISTS time_seconds NUMERIC(8,2);
ALTER TABLE public.game_results ADD COLUMN IF NOT EXISTS levels INTEGER;
ALTER TABLE public.game_results ADD COLUMN IF NOT EXISTS team_name TEXT;
ALTER TABLE public.game_results ALTER COLUMN user_id DROP NOT NULL;

CREATE INDEX IF NOT EXISTS idx_game_results_user_id ON public.game_results(user_id);
CREATE INDEX IF NOT EXISTS idx_game_results_player_name ON public.game_results(player_name);
CREATE INDEX IF NOT EXISTS idx_game_results_date ON public.game_results(date);
CREATE INDEX IF NOT EXISTS idx_game_results_game_mode ON public.game_results(game_mode);
CREATE INDEX IF NOT EXISTS idx_game_results_tournament_name ON public.game_results(tournament_name);

ALTER TABLE public.game_results ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'game_results' AND policyname = 'Allow public select game_results') THEN
    CREATE POLICY "Allow public select game_results" ON public.game_results FOR SELECT USING (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'game_results' AND policyname = 'Allow service role all game_results') THEN
    CREATE POLICY "Allow service role all game_results" ON public.game_results FOR ALL TO service_role USING (true);
  END IF;
END $$;

-- ==========================================
-- 8. TABELLE "achievements" (ERRUNGENSCHAFTEN)
-- ==========================================
CREATE TABLE IF NOT EXISTS public.achievements (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  is_guest BOOLEAN DEFAULT false,
  player_name TEXT,
  achievement_id TEXT NOT NULL,
  title TEXT NOT NULL,
  description TEXT,
  icon TEXT,
  rarity TEXT DEFAULT 'common',
  game_mode TEXT,
  earned_with TEXT[],
  earned_together BOOLEAN DEFAULT false,
  date TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Falls Tabelle schon existiert, fehlende Spalten idempotent ergänzen:
ALTER TABLE public.achievements ADD COLUMN IF NOT EXISTS is_guest BOOLEAN DEFAULT false;
ALTER TABLE public.achievements ADD COLUMN IF NOT EXISTS player_name TEXT;
ALTER TABLE public.achievements ALTER COLUMN user_id DROP NOT NULL;

CREATE INDEX IF NOT EXISTS idx_achievements_user_id ON public.achievements(user_id);
CREATE INDEX IF NOT EXISTS idx_achievements_player_name ON public.achievements(player_name);
CREATE INDEX IF NOT EXISTS idx_achievements_achievement_id ON public.achievements(achievement_id);
CREATE INDEX IF NOT EXISTS idx_achievements_date ON public.achievements(date);

ALTER TABLE public.achievements ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'achievements' AND policyname = 'Allow public select achievements') THEN
    CREATE POLICY "Allow public select achievements" ON public.achievements FOR SELECT USING (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'achievements' AND policyname = 'Allow service role all achievements') THEN
    CREATE POLICY "Allow service role all achievements" ON public.achievements FOR ALL TO service_role USING (true);
  END IF;
END $$;

-- ==========================================
-- 9. TABELLE "tournaments" (DYNAMIC SUPABASE TOURNAMENTS)
-- ==========================================
CREATE TABLE IF NOT EXISTS public.tournaments (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT UNIQUE NOT NULL,
  status TEXT NOT NULL DEFAULT 'In Vorbereitung',
  config JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_tournaments_name ON public.tournaments(name);
CREATE INDEX IF NOT EXISTS idx_tournaments_status ON public.tournaments(status);
CREATE INDEX IF NOT EXISTS idx_tournaments_created_at ON public.tournaments(created_at);

ALTER TABLE public.tournaments ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'tournaments' AND policyname = 'Allow public select tournaments') THEN
    CREATE POLICY "Allow public select tournaments" ON public.tournaments FOR SELECT USING (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'tournaments' AND policyname = 'Allow service role all tournaments') THEN
    CREATE POLICY "Allow service role all tournaments" ON public.tournaments FOR ALL TO service_role USING (true);
  END IF;
END $$;

